# Generated by Django 5.1.3 on 2026-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sastojak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_sastojka', models.CharField(max_length=255)),
                ('alergen', models.BooleanField(default=False)),
                ('tip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_jela', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('kategorija', models.CharField(max_length=50)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dostupno', models.BooleanField(default=True)),
                ('sastojci', models.ManyToManyField(related_name='jela', to='smart_menu_app.sastojak')),
            ],
        ),
    ]
